# Generated by Django 2.2.5 on 2019-10-01 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=9, max_digits=19, null=True)),
                ('created_a', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 1, 16, 3, 48, 560669, tzinfo=utc), null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='urlobject',
            name='url',
            field=models.TextField(),
        ),
    ]
